### ISSUE TITLE
DataBaseNew

### ISSUE THREAD

**Issue by CBarreraB** [Dium-dev/ATC_Back-end#192]
Necesitamos crear una base de datos nueva que contenga datos de categorías, marcas y productos para nuestra aplicación. Esta base de datos nos permitirá una ampliación de datos y facilitará las pruebas.

**Comment by CBarreraB** [comment]
Tareas:

- [ ]  Creación de la Base de Datos:

Crear una nueva base de datos para la aplicación. Asegurarse de que la base de datos esté configurada correctamente y sea accesible desde la aplicación. Esta se encuentra en:

https://docs.google.com/spreadsheets/d/1Og282LpUBbJW0bsMYGmiePeCLu7P0MGN/edit?usp=drive_link&ouid=113173239422684974206&rtpof=true&sd=true


- [ ]  Carga de Datos:

Cargar los datos de productos, incluyendo el título, descripción, precio, disponibilidad, categoría, marca y una imagen asociada.
Generar una lista de al menos 300 productos con títulos únicos y descripciones diversas.


- [ ] Relaciones en la Base de Datos:

Establecer relaciones en la base de datos para vincular productos con categorías y marcas.


- [ ] Pruebas y Verificación:

Realizar pruebas para asegurarse de que los datos se han cargado correctamente en la base de datos.

**Comment by CBarreraB** [comment]
Esta base de datos nueva es fundamental para el desarrollo y las pruebas en curso de la aplicación. Una vez completada, nos permitirá avanzar en el desarrollo de la funcionalidad de la aplicación con datos reales.

**Comment by leonel-cc** [comment]
Ya implemente la nueva base de datos, solo queda aceptar el pull request y mergearlo a development 👍
